FROM ruby:3.2.2

ENV RAILS_ENV=development

RUN apt update -qq && \
  apt install -y --no-install-recommends build-essential libpq-dev curl nodejs libvips-dev && \
  # curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg -o /root/yarn-pubkey.gpg && \
  # apt-key add /root/yarn-pubkey.gpg && \
  # echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
  # apt update && \
  # apt install -y --no-install-recommends nodejs yarn && \
  apt install -y --no-install-recommends nodejs && \
  apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile* ./
RUN bundle install -j $(nproc)

# COPY package.json yarn.lock ./
# RUN yarn install --ignore-scripts

CMD ["rails", "server", "-b", "0.0.0.0"]