name: BG worker to run persiodic tasks

on:
  schedule:
    # Once per week
    - cron: '0 0 * * 0'

jobs:
  # worker:
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@master
      # - name: Call server
        # run: wget http://translaite.com/start_clearing_chats_without_messages
  # blob_worker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Call server
  #       run: wget http://translaite.com/start_clearing_blobs
  sitemap_worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Call server
        run: wget http://margareti.com/refresh_sitemap